#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  9 21:22:19 2020

@author: shoo
"""

%matplotlib inline
from scipy import random
import numpy as np
import matplotlib.pyplot as plt

a = 0
b = np.pi #limits of integration
N = 1000
xrand = np.zeros(N)

for i in range(len(xrand)):
    xrand[i]= random.uniform(a,b)

def func(x):
    return np.sin(x)

integral = 0.0

for i in range(N):
    integral += func(xrand[i])
    
answer = (b-a)/float(N)*integral


areas = []

for i in range (N):
    xrand = np.zeros(N)

    for i in range(len(xrand)):
        xrand[i]= random.uniform(a,b)
        integral = 0.0

    for i in range(N):
        integral += func(xrand[i])
    
    answer = (b-a)/float(N)*integral
    areas.append(answer)
plt.title("Distribution of areas calculated")
plt.hist(areas,bins =30, ec = "black")
plt.xlabel("areas")

